/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import civitas.TituloPropiedad;
/**
 *
 * @author alejandro
 */
public class PropiedadPanel extends javax.swing.JPanel {
    
    TituloPropiedad tituloPropiedad;
    
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }

    public void setPropiedad(TituloPropiedad property){
        tituloPropiedad = property;
        setVisible(true);
        if(tituloPropiedad.getHipotecado())
            hipotecada.setText("Hipotecada");
        else
            hipotecada.setText("No hipotecada");
        
        nombre.setText(tituloPropiedad.getNombre());
        String aux = String.valueOf(tituloPropiedad.getNumCasas());
        num_casas.setText(aux);
        aux = String.valueOf(tituloPropiedad.getNumHoteles());
        num_hoteles.setText(aux);
        
        repaint();
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Name = new javax.swing.JLabel();
        Label_Casas = new javax.swing.JLabel();
        Label_Hoteles = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        num_casas = new javax.swing.JTextField();
        num_hoteles = new javax.swing.JTextField();
        hipotecada = new javax.swing.JTextField();

        Label_Name.setText("Nombre");
        Label_Name.setEnabled(false);

        Label_Casas.setText("Casas");
        Label_Casas.setEnabled(false);

        Label_Hoteles.setText("Hoteles");
        Label_Hoteles.setEnabled(false);

        nombre.setText("jTextField1");
        nombre.setEnabled(false);

        num_casas.setText("jTextField2");
        num_casas.setEnabled(false);

        num_hoteles.setText("jTextField3");
        num_hoteles.setEnabled(false);

        hipotecada.setText("jTextField4");
        hipotecada.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Label_Name)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Label_Casas)
                    .addComponent(num_casas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Label_Hoteles)
                    .addComponent(num_hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Name)
                    .addComponent(Label_Casas)
                    .addComponent(Label_Hoteles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_casas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Casas;
    private javax.swing.JLabel Label_Hoteles;
    private javax.swing.JLabel Label_Name;
    private javax.swing.JTextField hipotecada;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField num_casas;
    private javax.swing.JTextField num_hoteles;
    // End of variables declaration//GEN-END:variables
}
